# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/lithium/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/xiaomi/lithium/proprietary/bin/usf_proximity:system/bin/usf_proximity \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_General_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    vendor/xiaomi/lithium/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/lithium/proprietary/etc/camera/msm8996_camera.xml:system/etc/camera/msm8996_camera.xml \
    vendor/xiaomi/lithium/proprietary/etc/camera/ov16880_chromatix.xml:system/etc/camera/ov16880_chromatix.xml \
    vendor/xiaomi/lithium/proprietary/etc/camera/ov5675_primax_chromatix.xml:system/etc/camera/ov5675_primax_chromatix.xml \
    vendor/xiaomi/lithium/proprietary/etc/camera/s5k3p3_qtech_chromatix.xml:system/etc/camera/s5k3p3_qtech_chromatix.xml \
    vendor/xiaomi/lithium/proprietary/etc/elliptic_sensor.xml:system/etc/elliptic_sensor.xml \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/a530_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b00 \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/a530_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b01 \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/a530_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.b02 \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/a530_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.elf \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/a530_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_zap.mdt \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/tfa9891.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa9891.cnt \
    vendor/xiaomi/lithium/proprietary/vendor/etc/qdcm_calib_data_auo_fte716_1080p_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_auo_fte716_1080p_video_mode_dsi_panel.xml \
    vendor/xiaomi/lithium/proprietary/vendor/etc/qdcm_calib_data_sharp_fte716_1080p_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_sharp_fte716_1080p_video_mode_dsi_panel.xml \
    vendor/xiaomi/lithium/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/lithium/proprietary/etc/sensors/sensor_def_qcomdev.conf:system/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/lithium/proprietary/etc/silence_short.wav:system/etc/silence_short.wav \
    vendor/xiaomi/lithium/proprietary/etc/usf/form_factor_mtp.cfg:system/etc/usf/form_factor_mtp.cfg \
    vendor/xiaomi/lithium/proprietary/etc/usf/mixer/mixer_paths_mtp.xml:system/etc/usf/mixer/mixer_paths_mtp.xml \
    vendor/xiaomi/lithium/proprietary/etc/usf/proximity/cfg_mtp/usf_pocket_apps_mtp.cfg:system/etc/usf/proximity/cfg_mtp/usf_pocket_apps_mtp.cfg \
    vendor/xiaomi/lithium/proprietary/etc/usf/proximity/cfg_mtp/usf_pocket_mtp.cfg:system/etc/usf/proximity/cfg_mtp/usf_pocket_mtp.cfg \
    vendor/xiaomi/lithium/proprietary/etc/usf/proximity/cfg_mtp/usf_pocket_mtp_algo_transparent_data.bin:system/etc/usf/proximity/cfg_mtp/usf_pocket_mtp_algo_transparent_data.bin \
    vendor/xiaomi/lithium/proprietary/etc/usf/proximity/cfg_mtp/usf_proximity_apps_mtp.cfg:system/etc/usf/proximity/cfg_mtp/usf_proximity_apps_mtp.cfg \
    vendor/xiaomi/lithium/proprietary/etc/usf/proximity/cfg_mtp/usf_proximity_mtp.cfg:system/etc/usf/proximity/cfg_mtp/usf_proximity_mtp.cfg \
    vendor/xiaomi/lithium/proprietary/etc/usf/proximity/cfg_mtp/usf_proximity_mtp_algo_transparent_data.bin:system/etc/usf/proximity/cfg_mtp/usf_proximity_mtp_algo_transparent_data.bin \
    vendor/xiaomi/lithium/proprietary/etc/usf/proximity/cfg_mtp/usf_proximity_mtp_debug.cfg:system/etc/usf/proximity/cfg_mtp/usf_proximity_mtp_debug.cfg \
    vendor/xiaomi/lithium/proprietary/etc/usf/proximity/cfg_mtp/usf_proximity_mtp_rx_transparent_data.bin:system/etc/usf/proximity/cfg_mtp/usf_proximity_mtp_rx_transparent_data.bin \
    vendor/xiaomi/lithium/proprietary/etc/usf/proximity/cfg_mtp/usf_proximity_mtp_tx_transparent_data.bin:system/etc/usf/proximity/cfg_mtp/usf_proximity_mtp_tx_transparent_data.bin \
    vendor/xiaomi/lithium/proprietary/etc/usf/proximity/cfg_mtp/usf_ranging_apps_mtp.cfg:system/etc/usf/proximity/cfg_mtp/usf_ranging_apps_mtp.cfg \
    vendor/xiaomi/lithium/proprietary/etc/usf/proximity/cfg_mtp/usf_ranging_mtp_algo_transparent_data.bin:system/etc/usf/proximity/cfg_mtp/usf_ranging_mtp_algo_transparent_data.bin \
    vendor/xiaomi/lithium/proprietary/etc/usf/readme.txt:system/etc/usf/readme.txt \
    vendor/xiaomi/lithium/proprietary/etc/usf/version.txt:system/etc/usf/version.txt \
    vendor/xiaomi/lithium/proprietary/lib/hw/fingerprint.fpc.so:system/lib/hw/fingerprint.fpc.so \
    vendor/xiaomi/lithium/proprietary/lib/libultrasound.so:system/lib/libultrasound.so \
    vendor/xiaomi/lithium/proprietary/lib64/hw/fingerprint.fpc.so:system/lib64/hw/fingerprint.fpc.so \
    vendor/xiaomi/lithium/proprietary/lib64/libnotifyaudiohal.so:system/lib64/libnotifyaudiohal.so \
    vendor/xiaomi/lithium/proprietary/lib64/libultrasound.so:system/lib64/libultrasound.so \
    vendor/xiaomi/lithium/proprietary/usr/idc/usf_tsc.idc:system/usr/idc/usf_tsc.idc \
    vendor/xiaomi/lithium/proprietary/usr/idc/usf_tsc_ext.idc:system/usr/idc/usf_tsc_ext.idc \
    vendor/xiaomi/lithium/proprietary/usr/idc/usf_tsc_ptr.idc:system/usr/idc/usf_tsc_ptr.idc \
    vendor/xiaomi/lithium/proprietary/vendor/firmware/libpn551_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn551_fw.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libactuator_dw9763_a8_o-film.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9763_a8_o-film.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libactuator_dw9763_a8_qtech.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9763_a8_qtech.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_common.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_cpp_hfr_120.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_cpp_hfr_60.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_cpp_hfr_90.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_cpp_liveshot.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_cpp_preview.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_cpp_snapshot.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_cpp_video.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_default_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_default_preview_3a.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_default_video.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_default_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_default_video_3a.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_hfr_120.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_hfr_120_3a.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_hfr_60.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_hfr_60_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_hfr_60_3a.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_hfr_90.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_hfr_90_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_hfr_90_3a.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_liveshot.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_postproc.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_preview.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_snapshot.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_zsl_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_zsl_preview_3a.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov16880_zsl_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov16880_zsl_video_3a.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_a3_default_preview.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_a3_default_video.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_a3_hfr_120.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_a3_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_a3_hfr_60.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_a3_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_a3_hfr_90.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_common.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_cpp_ds_chromatix.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_cpp_hfr_120.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_cpp_hfr_60.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_cpp_hfr_90.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_cpp_liveshot.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_cpp_preview.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_cpp_snapshot.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_cpp_us_chromatix.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_cpp_video.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_cpp_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_cpp_video_full.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_default_video.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_hfr_120.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_hfr_60.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_hfr_90.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_postproc.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_preview.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_snapshot.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_video_full.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_zsl_preview.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_ov5675_primax_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_primax_zsl_video.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_common.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_cpp_hfr_120.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_cpp_hfr_60.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_cpp_hfr_90.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_cpp_liveshot.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_cpp_preview.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_cpp_snapshot.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_cpp_video.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_default_preview.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_default_video.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_hfr_120.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_hfr_120_3a.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_hfr_60.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_hfr_60_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_hfr_60_3a.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_hfr_90.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_hfr_90_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_hfr_90_3a.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_liveshot.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_postproc.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_preview.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_snapshot.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_zsl_preview.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libchromatix_s5k3p3_qtech_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_qtech_zsl_video.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libmmcamera_ov16880.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov16880.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libmmcamera_ov16880_ofilm_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov16880_ofilm_eeprom.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libmmcamera_ov5675_primax.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov5675_primax.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libmmcamera_s5k3p3_qtech.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3p3_qtech.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libmmcamera_s5k3p3_qtech_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3p3_qtech_eeprom.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libproxadapter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libproxadapter.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libproxsockadapter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libproxsockadapter.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libual.so:$(TARGET_COPY_OUT_VENDOR)/lib/libual.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libualutil.so:$(TARGET_COPY_OUT_VENDOR)/lib/libualutil.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib/libusndroute.so:$(TARGET_COPY_OUT_VENDOR)/lib/libusndroute.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib64/libproxadapter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libproxadapter.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib64/libproxsockadapter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libproxsockadapter.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib64/libqcproximity.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqcproximity.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib64/libual.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libual.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib64/libualutil.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libualutil.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib64/libusndroute.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libusndroute.so \
    vendor/xiaomi/lithium/proprietary/vendor/lib64/sensors.elliptic.so:$(TARGET_COPY_OUT_VENDOR)/lib64/sensors.elliptic.so
