# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/chiron/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/xiaomi/chiron/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/chiron/proprietary/vendor/etc/camera/chiron_imx386_semco_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/chiron_imx386_semco_chromatix.xml \
    vendor/xiaomi/chiron/proprietary/vendor/etc/camera/chiron_ov5675_primax_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/chiron_ov5675_primax_chromatix.xml \
    vendor/xiaomi/chiron/proprietary/vendor/etc/camera/chiron_ov5675_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/chiron_ov5675_qtech_chromatix.xml \
    vendor/xiaomi/chiron/proprietary/vendor/etc/dualcamera.png:$(TARGET_COPY_OUT_VENDOR)/etc/dualcamera.png \
    vendor/xiaomi/chiron/proprietary/vendor/etc/elliptic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/elliptic.xml \
    vendor/xiaomi/chiron/proprietary/vendor/firmware/tas2559_s_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2559_s_uCDSP.bin \
    vendor/xiaomi/chiron/proprietary/vendor/firmware/tas2559_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2559_uCDSP.bin \
    vendor/xiaomi/chiron/proprietary/vendor/etc/qdcm_calib_data_jdi_fhd_video_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_jdi_fhd_video_dsi_panel.xml \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/libnotifyaudiohal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnotifyaudiohal.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/libultrasound.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libultrasound.so \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Bluetooth_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_General_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Global_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Handset_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Hdmi_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Headset_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Speaker_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_workspaceFile.qwsp \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_General_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/Forte/Forte_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_workspaceFile.qwsp \
    vendor/xiaomi/chiron/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/chiron/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/chiron/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/chiron/proprietary/vendor/etc/thermal-engine-8998.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-8998.conf \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libactuator_chiron_imx386_ak7372_semco.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_chiron_imx386_ak7372_semco.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_4K_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_4K_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_4K_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_4K_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_common.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_cpp_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_cpp_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_cpp_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_cpp_liveshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_cpp_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_cpp_snapshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_snapshot_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_cpp_snapshot_hdr.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_snapshot_hht.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_cpp_snapshot_hht.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_cpp_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_cpp_video_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_cpp_video_hdr.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_default_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_default_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hdr_snapshot_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_hdr_snapshot_3a.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hdr_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_hdr_video_3a.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_hfr_120_3a.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hfr_60_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_hfr_60_3a.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_hfr_90_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_hfr_90_3a.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_liveshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_postproc.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_snapshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_snapshot_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_snapshot_hdr.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_video_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_video_hdr.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_zsl_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_imx386_semco_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_imx386_semco_zsl_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_a3_default_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_a3_default_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_a3_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_a3_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_a3_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_a3_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_a3_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_common.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_cpp_ds_chromatix.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_cpp_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_cpp_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_cpp_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_cpp_liveshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_cpp_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_cpp_snapshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_cpp_us_chromatix.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_cpp_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_cpp_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_cpp_video_full.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_default_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_liveshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_postproc.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_snapshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_video_full.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_zsl_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_primax_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_primax_zsl_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_a3_default_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_a3_default_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_a3_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_a3_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_a3_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_a3_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_common.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_cpp_ds_chromatix.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_cpp_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_cpp_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_cpp_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_cpp_liveshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_cpp_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_cpp_snapshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_cpp_us_chromatix.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_cpp_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_cpp_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_cpp_video_full.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_default_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_hfr_120.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_hfr_60.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_hfr_90.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_liveshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_postproc.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_snapshot.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_video_full.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_zsl_preview.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libchromatix_chiron_ov5675_qtech_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_chiron_ov5675_qtech_zsl_video.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libmmcamera_chiron_imx386_semco.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_chiron_imx386_semco.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libmmcamera_chiron_imx386_semco_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_chiron_imx386_semco_eeprom.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libmmcamera_chiron_ov5675_primax.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_chiron_ov5675_primax.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libmmcamera_chiron_ov5675_primax_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_chiron_ov5675_primax_eeprom.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libmmcamera_chiron_ov5675_qtech.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_chiron_ov5675_qtech.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib/libmmcamera_chiron_ov5675_qtech_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_chiron_ov5675_qtech_eeprom.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/com.fingerprints.extension@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.fingerprints.extension@1.0.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/hw/fingerprint.fpc.msm8998.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.fpc.msm8998.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/hw/fingerprint.goodix.msm8998.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.goodix.msm8998.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/libgf_ca.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgf_ca.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/libgf_hal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgf_hal.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/sensors.elliptic.so:$(TARGET_COPY_OUT_VENDOR)/lib64/sensors.elliptic.so \
    vendor/xiaomi/chiron/proprietary/vendor/lib64/vendor.goodix.hardware.fingerprintextension@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.goodix.hardware.fingerprintextension@1.0.so
