# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/gemini/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/xiaomi/gemini/proprietary/etc/acdbdata/adsp_avs_config.acdb:system/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/gemini/proprietary/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:system/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    vendor/xiaomi/gemini/proprietary/etc/acdbdata/Forte/Forte_General_cal.acdb:system/etc/acdbdata/Forte/Forte_General_cal.acdb \
    vendor/xiaomi/gemini/proprietary/etc/acdbdata/Forte/Forte_Global_cal.acdb:system/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    vendor/xiaomi/gemini/proprietary/etc/acdbdata/Forte/Forte_Handset_cal.acdb:system/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    vendor/xiaomi/gemini/proprietary/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:system/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    vendor/xiaomi/gemini/proprietary/etc/acdbdata/Forte/Forte_Headset_cal.acdb:system/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    vendor/xiaomi/gemini/proprietary/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:system/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    vendor/xiaomi/gemini/proprietary/etc/camera/imx298_liteon_chromatix.xml:system/etc/camera/imx298_liteon_chromatix.xml \
    vendor/xiaomi/gemini/proprietary/etc/camera/imx298_semco_chromatix.xml:system/etc/camera/imx298_semco_chromatix.xml \
    vendor/xiaomi/gemini/proprietary/etc/camera/msm8996_camera.xml:system/etc/camera/msm8996_camera.xml \
    vendor/xiaomi/gemini/proprietary/etc/camera/ov4688_chromatix.xml:system/etc/camera/ov4688_chromatix.xml \
    vendor/xiaomi/gemini/proprietary/etc/camera/ov4688_primax_chromatix.xml:system/etc/camera/ov4688_primax_chromatix.xml \
    vendor/xiaomi/gemini/proprietary/etc/firmware/a530_zap.b00:system/etc/firmware/a530_zap.b00 \
    vendor/xiaomi/gemini/proprietary/etc/firmware/a530_zap.b01:system/etc/firmware/a530_zap.b01 \
    vendor/xiaomi/gemini/proprietary/etc/firmware/a530_zap.b02:system/etc/firmware/a530_zap.b02 \
    vendor/xiaomi/gemini/proprietary/etc/firmware/a530_zap.elf:system/etc/firmware/a530_zap.elf \
    vendor/xiaomi/gemini/proprietary/etc/firmware/a530_zap.mdt:system/etc/firmware/a530_zap.mdt \
    vendor/xiaomi/gemini/proprietary/etc/firmware/tfa9891.cnt:system/etc/firmware/tfa9891.cnt \
    vendor/xiaomi/gemini/proprietary/etc/firmware/tfa98xx.cnt:system/etc/firmware/tfa98xx.cnt \
    vendor/xiaomi/gemini/proprietary/lib64/hw/consumerir.msm8996.so:system/lib64/hw/consumerir.msm8996.so \
    vendor/xiaomi/gemini/proprietary/lib64/hw/fingerprint.fpc.so:system/lib64/hw/fingerprint.fpc.so \
    vendor/xiaomi/gemini/proprietary/lib/hw/consumerir.msm8996.so:system/lib/hw/consumerir.msm8996.so \
    vendor/xiaomi/gemini/proprietary/lib/hw/fingerprint.fpc.so:system/lib/hw/fingerprint.fpc.so \
    vendor/xiaomi/gemini/proprietary/vendor/firmware/libpn548ad_fw.so:system/vendor/firmware/libpn548ad_fw.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libactuator_ak7348.so:system/vendor/lib/libactuator_ak7348.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libactuator_ak7371.so:system/vendor/lib/libactuator_ak7371.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_4K_preview.so:system/vendor/lib/libchromatix_imx298_liteon_4K_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_4K_video.so:system/vendor/lib/libchromatix_imx298_liteon_4K_video.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_common.so:system/vendor/lib/libchromatix_imx298_liteon_common.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_cpp_hfr_120.so:system/vendor/lib/libchromatix_imx298_liteon_cpp_hfr_120.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_cpp_hfr_60.so:system/vendor/lib/libchromatix_imx298_liteon_cpp_hfr_60.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_cpp_hfr_90.so:system/vendor/lib/libchromatix_imx298_liteon_cpp_hfr_90.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_cpp_liveshot.so:system/vendor/lib/libchromatix_imx298_liteon_cpp_liveshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_cpp_preview.so:system/vendor/lib/libchromatix_imx298_liteon_cpp_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_cpp_snapshot_hdr.so:system/vendor/lib/libchromatix_imx298_liteon_cpp_snapshot_hdr.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_cpp_snapshot.so:system/vendor/lib/libchromatix_imx298_liteon_cpp_snapshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_cpp_video_hdr.so:system/vendor/lib/libchromatix_imx298_liteon_cpp_video_hdr.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_cpp_video.so:system/vendor/lib/libchromatix_imx298_liteon_cpp_video.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_default_preview.so:system/vendor/lib/libchromatix_imx298_liteon_default_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_default_video.so:system/vendor/lib/libchromatix_imx298_liteon_default_video.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_hdr_snapshot_3a.so:system/vendor/lib/libchromatix_imx298_liteon_hdr_snapshot_3a.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_hdr_video_3a.so:system/vendor/lib/libchromatix_imx298_liteon_hdr_video_3a.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_hfr_120_3a.so:system/vendor/lib/libchromatix_imx298_liteon_hfr_120_3a.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_hfr_120.so:system/vendor/lib/libchromatix_imx298_liteon_hfr_120.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_hfr_60_3a.so:system/vendor/lib/libchromatix_imx298_liteon_hfr_60_3a.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_hfr_60.so:system/vendor/lib/libchromatix_imx298_liteon_hfr_60.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_hfr_90_3a.so:system/vendor/lib/libchromatix_imx298_liteon_hfr_90_3a.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_hfr_90.so:system/vendor/lib/libchromatix_imx298_liteon_hfr_90.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_liveshot.so:system/vendor/lib/libchromatix_imx298_liteon_liveshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_postproc.so:system/vendor/lib/libchromatix_imx298_liteon_postproc.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_preview.so:system/vendor/lib/libchromatix_imx298_liteon_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_snapshot_hdr.so:system/vendor/lib/libchromatix_imx298_liteon_snapshot_hdr.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_snapshot.so:system/vendor/lib/libchromatix_imx298_liteon_snapshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_video_hdr.so:system/vendor/lib/libchromatix_imx298_liteon_video_hdr.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_zsl_preview.so:system/vendor/lib/libchromatix_imx298_liteon_zsl_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_liteon_zsl_video.so:system/vendor/lib/libchromatix_imx298_liteon_zsl_video.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_4K_preview.so:system/vendor/lib/libchromatix_imx298_semco_4K_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_4K_video.so:system/vendor/lib/libchromatix_imx298_semco_4K_video.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_common.so:system/vendor/lib/libchromatix_imx298_semco_common.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_cpp_hfr_120.so:system/vendor/lib/libchromatix_imx298_semco_cpp_hfr_120.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_cpp_hfr_60.so:system/vendor/lib/libchromatix_imx298_semco_cpp_hfr_60.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_cpp_hfr_90.so:system/vendor/lib/libchromatix_imx298_semco_cpp_hfr_90.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_cpp_liveshot.so:system/vendor/lib/libchromatix_imx298_semco_cpp_liveshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_cpp_preview.so:system/vendor/lib/libchromatix_imx298_semco_cpp_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_cpp_snapshot_hdr.so:system/vendor/lib/libchromatix_imx298_semco_cpp_snapshot_hdr.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_cpp_snapshot.so:system/vendor/lib/libchromatix_imx298_semco_cpp_snapshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_cpp_video_hdr.so:system/vendor/lib/libchromatix_imx298_semco_cpp_video_hdr.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_cpp_video.so:system/vendor/lib/libchromatix_imx298_semco_cpp_video.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_default_preview.so:system/vendor/lib/libchromatix_imx298_semco_default_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_default_video.so:system/vendor/lib/libchromatix_imx298_semco_default_video.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_hdr_snapshot_3a.so:system/vendor/lib/libchromatix_imx298_semco_hdr_snapshot_3a.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_hdr_video_3a.so:system/vendor/lib/libchromatix_imx298_semco_hdr_video_3a.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_hfr_120_3a.so:system/vendor/lib/libchromatix_imx298_semco_hfr_120_3a.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_hfr_120.so:system/vendor/lib/libchromatix_imx298_semco_hfr_120.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_hfr_60_3a.so:system/vendor/lib/libchromatix_imx298_semco_hfr_60_3a.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_hfr_60.so:system/vendor/lib/libchromatix_imx298_semco_hfr_60.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_hfr_90_3a.so:system/vendor/lib/libchromatix_imx298_semco_hfr_90_3a.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_hfr_90.so:system/vendor/lib/libchromatix_imx298_semco_hfr_90.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_liveshot.so:system/vendor/lib/libchromatix_imx298_semco_liveshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_postproc.so:system/vendor/lib/libchromatix_imx298_semco_postproc.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_preview.so:system/vendor/lib/libchromatix_imx298_semco_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_snapshot_hdr.so:system/vendor/lib/libchromatix_imx298_semco_snapshot_hdr.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_snapshot.so:system/vendor/lib/libchromatix_imx298_semco_snapshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_video_hdr.so:system/vendor/lib/libchromatix_imx298_semco_video_hdr.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_zsl_preview.so:system/vendor/lib/libchromatix_imx298_semco_zsl_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_imx298_semco_zsl_video.so:system/vendor/lib/libchromatix_imx298_semco_zsl_video.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_common.so:system/vendor/lib/libchromatix_ov4688_common.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_cpp_hfr_120.so:system/vendor/lib/libchromatix_ov4688_cpp_hfr_120.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_cpp_hfr_60.so:system/vendor/lib/libchromatix_ov4688_cpp_hfr_60.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_cpp_hfr_90.so:system/vendor/lib/libchromatix_ov4688_cpp_hfr_90.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_cpp_liveshot.so:system/vendor/lib/libchromatix_ov4688_cpp_liveshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_cpp_preview.so:system/vendor/lib/libchromatix_ov4688_cpp_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_cpp_snapshot.so:system/vendor/lib/libchromatix_ov4688_cpp_snapshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_cpp_video.so:system/vendor/lib/libchromatix_ov4688_cpp_video.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_default_video.so:system/vendor/lib/libchromatix_ov4688_default_video.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_hfr_120_ad5823.so:system/vendor/lib/libchromatix_ov4688_hfr_120_ad5823.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_hfr_120.so:system/vendor/lib/libchromatix_ov4688_hfr_120.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_hfr_60_ad5823.so:system/vendor/lib/libchromatix_ov4688_hfr_60_ad5823.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_hfr_60.so:system/vendor/lib/libchromatix_ov4688_hfr_60.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_hfr_90_ad5823.so:system/vendor/lib/libchromatix_ov4688_hfr_90_ad5823.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_hfr_90.so:system/vendor/lib/libchromatix_ov4688_hfr_90.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_liveshot.so:system/vendor/lib/libchromatix_ov4688_liveshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_postproc.so:system/vendor/lib/libchromatix_ov4688_postproc.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_preview.so:system/vendor/lib/libchromatix_ov4688_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_common.so:system/vendor/lib/libchromatix_ov4688_primax_common.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_cpp_hfr_120.so:system/vendor/lib/libchromatix_ov4688_primax_cpp_hfr_120.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_cpp_hfr_60.so:system/vendor/lib/libchromatix_ov4688_primax_cpp_hfr_60.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_cpp_hfr_90.so:system/vendor/lib/libchromatix_ov4688_primax_cpp_hfr_90.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_cpp_liveshot.so:system/vendor/lib/libchromatix_ov4688_primax_cpp_liveshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_cpp_preview.so:system/vendor/lib/libchromatix_ov4688_primax_cpp_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_cpp_snapshot.so:system/vendor/lib/libchromatix_ov4688_primax_cpp_snapshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_cpp_video.so:system/vendor/lib/libchromatix_ov4688_primax_cpp_video.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_default_video.so:system/vendor/lib/libchromatix_ov4688_primax_default_video.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_hfr_120_ad5823.so:system/vendor/lib/libchromatix_ov4688_primax_hfr_120_ad5823.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_hfr_120.so:system/vendor/lib/libchromatix_ov4688_primax_hfr_120.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_hfr_60_ad5823.so:system/vendor/lib/libchromatix_ov4688_primax_hfr_60_ad5823.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_hfr_60.so:system/vendor/lib/libchromatix_ov4688_primax_hfr_60.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_hfr_90_ad5823.so:system/vendor/lib/libchromatix_ov4688_primax_hfr_90_ad5823.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_hfr_90.so:system/vendor/lib/libchromatix_ov4688_primax_hfr_90.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_liveshot.so:system/vendor/lib/libchromatix_ov4688_primax_liveshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_postproc.so:system/vendor/lib/libchromatix_ov4688_primax_postproc.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_preview.so:system/vendor/lib/libchromatix_ov4688_primax_preview.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_snapshot.so:system/vendor/lib/libchromatix_ov4688_primax_snapshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_zsl_preview_ad5823.so:system/vendor/lib/libchromatix_ov4688_primax_zsl_preview_ad5823.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_primax_zsl_video_ad5823.so:system/vendor/lib/libchromatix_ov4688_primax_zsl_video_ad5823.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_snapshot.so:system/vendor/lib/libchromatix_ov4688_snapshot.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_zsl_preview_ad5823.so:system/vendor/lib/libchromatix_ov4688_zsl_preview_ad5823.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libchromatix_ov4688_zsl_video_ad5823.so:system/vendor/lib/libchromatix_ov4688_zsl_video_ad5823.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libmmcamera_imx298_liteon.so:system/vendor/lib/libmmcamera_imx298_liteon.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libmmcamera_imx298_semco.so:system/vendor/lib/libmmcamera_imx298_semco.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libmmcamera_imx298.so:system/vendor/lib/libmmcamera_imx298.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libmmcamera_ov4688_eeprom.so:system/vendor/lib/libmmcamera_ov4688_eeprom.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libmmcamera_ov4688_primax.so:system/vendor/lib/libmmcamera_ov4688_primax.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libmmcamera_ov4688.so:system/vendor/lib/libmmcamera_ov4688.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libmmcamera_sony_imx298_eeprom.so:system/vendor/lib/libmmcamera_sony_imx298_eeprom.so \
    vendor/xiaomi/gemini/proprietary/vendor/lib/libSonyIMX298PdafLibrary.so:system/vendor/lib/libSonyIMX298PdafLibrary.so
