# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/scorpio/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/xiaomi/scorpio/proprietary/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:system/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    vendor/xiaomi/scorpio/proprietary/etc/acdbdata/Forte/Forte_General_cal.acdb:system/etc/acdbdata/Forte/Forte_General_cal.acdb \
    vendor/xiaomi/scorpio/proprietary/etc/acdbdata/Forte/Forte_Global_cal.acdb:system/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    vendor/xiaomi/scorpio/proprietary/etc/acdbdata/Forte/Forte_Handset_cal.acdb:system/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    vendor/xiaomi/scorpio/proprietary/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:system/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    vendor/xiaomi/scorpio/proprietary/etc/acdbdata/Forte/Forte_Headset_cal.acdb:system/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    vendor/xiaomi/scorpio/proprietary/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:system/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    vendor/xiaomi/scorpio/proprietary/etc/acdbdata/adsp_avs_config.acdb:system/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/scorpio/proprietary/etc/camera/imx268_chromatix.xml:system/etc/camera/imx268_chromatix.xml \
    vendor/xiaomi/scorpio/proprietary/etc/camera/imx268_sunny_chromatix.xml:system/etc/camera/imx268_sunny_chromatix.xml \
    vendor/xiaomi/scorpio/proprietary/etc/camera/imx318_chromatix.xml:system/etc/camera/imx318_chromatix.xml \
    vendor/xiaomi/scorpio/proprietary/etc/camera/imx318_primax_chromatix.xml:system/etc/camera/imx318_primax_chromatix.xml \
    vendor/xiaomi/scorpio/proprietary/etc/camera/imx318_semco_chromatix.xml:system/etc/camera/imx318_semco_chromatix.xml \
    vendor/xiaomi/scorpio/proprietary/etc/camera/msm8996_camera.xml:system/etc/camera/msm8996_camera.xml \
    vendor/xiaomi/scorpio/proprietary/etc/firmware/a530_zap.b00:system/etc/firmware/a530_zap.b00 \
    vendor/xiaomi/scorpio/proprietary/etc/firmware/a530_zap.b01:system/etc/firmware/a530_zap.b01 \
    vendor/xiaomi/scorpio/proprietary/etc/firmware/a530_zap.b02:system/etc/firmware/a530_zap.b02 \
    vendor/xiaomi/scorpio/proprietary/etc/firmware/a530_zap.elf:system/etc/firmware/a530_zap.elf \
    vendor/xiaomi/scorpio/proprietary/etc/firmware/a530_zap.mdt:system/etc/firmware/a530_zap.mdt \
    vendor/xiaomi/scorpio/proprietary/vendor/etc/sensors/hals.conf:system/vendor/etc/sensors/hals.conf \
    vendor/xiaomi/scorpio/proprietary/etc/sensors/sensor_def_qcomdev.conf:system/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/scorpio/proprietary/etc/thermal-engine-8996.conf:system/etc/thermal-engine-8996.conf \
    vendor/xiaomi/scorpio/proprietary/lib/hw/fingerprint.fpc.so:system/lib/hw/fingerprint.fpc.so \
    vendor/xiaomi/scorpio/proprietary/lib64/hw/fingerprint.fpc.so:system/lib64/hw/fingerprint.fpc.so \
    vendor/xiaomi/scorpio/proprietary/vendor/firmware/libpn548ad_fw.so:system/vendor/firmware/libpn548ad_fw.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libSonyIMX318PdafLibrary.so:system/vendor/lib/libSonyIMX318PdafLibrary.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libactuator_ak7371_a4_primax.so:system/vendor/lib/libactuator_ak7371_a4_primax.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libactuator_bu64245.so:system/vendor/lib/libactuator_bu64245.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libactuator_lc898214xc.so:system/vendor/lib/libactuator_lc898214xc.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libactuator_lc898217xc_a4_semco.so:system/vendor/lib/libactuator_lc898217xc_a4_semco.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_common.so:system/vendor/lib/libchromatix_imx268_common.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_cpp_hfr_120.so:system/vendor/lib/libchromatix_imx268_cpp_hfr_120.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_cpp_hfr_60.so:system/vendor/lib/libchromatix_imx268_cpp_hfr_60.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_cpp_hfr_90.so:system/vendor/lib/libchromatix_imx268_cpp_hfr_90.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_cpp_liveshot.so:system/vendor/lib/libchromatix_imx268_cpp_liveshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_cpp_preview.so:system/vendor/lib/libchromatix_imx268_cpp_preview.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_cpp_snapshot.so:system/vendor/lib/libchromatix_imx268_cpp_snapshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_cpp_video.so:system/vendor/lib/libchromatix_imx268_cpp_video.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_default_video.so:system/vendor/lib/libchromatix_imx268_default_video.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_hfr_120.so:system/vendor/lib/libchromatix_imx268_hfr_120.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_hfr_120_bu64245.so:system/vendor/lib/libchromatix_imx268_hfr_120_bu64245.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_hfr_60.so:system/vendor/lib/libchromatix_imx268_hfr_60.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_hfr_60_bu64245.so:system/vendor/lib/libchromatix_imx268_hfr_60_bu64245.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_hfr_90.so:system/vendor/lib/libchromatix_imx268_hfr_90.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_hfr_90_bu64245.so:system/vendor/lib/libchromatix_imx268_hfr_90_bu64245.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_postproc.so:system/vendor/lib/libchromatix_imx268_postproc.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_preview.so:system/vendor/lib/libchromatix_imx268_preview.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_snapshot.so:system/vendor/lib/libchromatix_imx268_snapshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_common.so:system/vendor/lib/libchromatix_imx268_sunny_common.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_cpp_hfr_120.so:system/vendor/lib/libchromatix_imx268_sunny_cpp_hfr_120.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_cpp_hfr_60.so:system/vendor/lib/libchromatix_imx268_sunny_cpp_hfr_60.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_cpp_hfr_90.so:system/vendor/lib/libchromatix_imx268_sunny_cpp_hfr_90.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_cpp_liveshot.so:system/vendor/lib/libchromatix_imx268_sunny_cpp_liveshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_cpp_preview.so:system/vendor/lib/libchromatix_imx268_sunny_cpp_preview.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_cpp_snapshot.so:system/vendor/lib/libchromatix_imx268_sunny_cpp_snapshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_cpp_video.so:system/vendor/lib/libchromatix_imx268_sunny_cpp_video.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_default_video.so:system/vendor/lib/libchromatix_imx268_sunny_default_video.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_hfr_120.so:system/vendor/lib/libchromatix_imx268_sunny_hfr_120.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_hfr_120_bu64245.so:system/vendor/lib/libchromatix_imx268_sunny_hfr_120_bu64245.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_hfr_60.so:system/vendor/lib/libchromatix_imx268_sunny_hfr_60.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_hfr_60_bu64245.so:system/vendor/lib/libchromatix_imx268_sunny_hfr_60_bu64245.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_hfr_90.so:system/vendor/lib/libchromatix_imx268_sunny_hfr_90.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_hfr_90_bu64245.so:system/vendor/lib/libchromatix_imx268_sunny_hfr_90_bu64245.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_postproc.so:system/vendor/lib/libchromatix_imx268_sunny_postproc.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_preview.so:system/vendor/lib/libchromatix_imx268_sunny_preview.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_snapshot.so:system/vendor/lib/libchromatix_imx268_sunny_snapshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_zsl_preview_bu64245.so:system/vendor/lib/libchromatix_imx268_sunny_zsl_preview_bu64245.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_sunny_zsl_video_bu64245.so:system/vendor/lib/libchromatix_imx268_sunny_zsl_video_bu64245.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_zsl_preview_bu64245.so:system/vendor/lib/libchromatix_imx268_zsl_preview_bu64245.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx268_zsl_video_bu64245.so:system/vendor/lib/libchromatix_imx268_zsl_video_bu64245.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_common.so:system/vendor/lib/libchromatix_imx318_common.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_cpp_hfr_120.so:system/vendor/lib/libchromatix_imx318_cpp_hfr_120.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_cpp_hfr_240.so:system/vendor/lib/libchromatix_imx318_cpp_hfr_240.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_cpp_hfr_60.so:system/vendor/lib/libchromatix_imx318_cpp_hfr_60.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_cpp_liveshot.so:system/vendor/lib/libchromatix_imx318_cpp_liveshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_cpp_preview.so:system/vendor/lib/libchromatix_imx318_cpp_preview.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_cpp_snapshot.so:system/vendor/lib/libchromatix_imx318_cpp_snapshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_cpp_video.so:system/vendor/lib/libchromatix_imx318_cpp_video.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_cpp_video_4k.so:system/vendor/lib/libchromatix_imx318_cpp_video_4k.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_hfr_120.so:system/vendor/lib/libchromatix_imx318_hfr_120.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_hfr_240.so:system/vendor/lib/libchromatix_imx318_hfr_240.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_hfr_240_lc898214xc.so:system/vendor/lib/libchromatix_imx318_hfr_240_lc898214xc.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_hfr_60.so:system/vendor/lib/libchromatix_imx318_hfr_60.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_postproc.so:system/vendor/lib/libchromatix_imx318_postproc.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_preview.so:system/vendor/lib/libchromatix_imx318_preview.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_1080p_preview_ak7371.so:system/vendor/lib/libchromatix_imx318_primax_1080p_preview_ak7371.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_1080p_video_ak7371.so:system/vendor/lib/libchromatix_imx318_primax_1080p_video_ak7371.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_4k_preview_ak7371.so:system/vendor/lib/libchromatix_imx318_primax_4k_preview_ak7371.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_4k_video_ak7371.so:system/vendor/lib/libchromatix_imx318_primax_4k_video_ak7371.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_common.so:system/vendor/lib/libchromatix_imx318_primax_common.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_cpp_hfr_120.so:system/vendor/lib/libchromatix_imx318_primax_cpp_hfr_120.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_cpp_hfr_240.so:system/vendor/lib/libchromatix_imx318_primax_cpp_hfr_240.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_cpp_hfr_60.so:system/vendor/lib/libchromatix_imx318_primax_cpp_hfr_60.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_cpp_liveshot.so:system/vendor/lib/libchromatix_imx318_primax_cpp_liveshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_cpp_preview.so:system/vendor/lib/libchromatix_imx318_primax_cpp_preview.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_cpp_snapshot.so:system/vendor/lib/libchromatix_imx318_primax_cpp_snapshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_cpp_video.so:system/vendor/lib/libchromatix_imx318_primax_cpp_video.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_cpp_video_4k.so:system/vendor/lib/libchromatix_imx318_primax_cpp_video_4k.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_default_preview_ak7371.so:system/vendor/lib/libchromatix_imx318_primax_default_preview_ak7371.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_default_video_ak7371.so:system/vendor/lib/libchromatix_imx318_primax_default_video_ak7371.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_fullsize_preview_ak7371.so:system/vendor/lib/libchromatix_imx318_primax_fullsize_preview_ak7371.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_fullsize_video_ak7371.so:system/vendor/lib/libchromatix_imx318_primax_fullsize_video_ak7371.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_hfr_120.so:system/vendor/lib/libchromatix_imx318_primax_hfr_120.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_hfr_120_ak7371.so:system/vendor/lib/libchromatix_imx318_primax_hfr_120_ak7371.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_hfr_240.so:system/vendor/lib/libchromatix_imx318_primax_hfr_240.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_hfr_240_ak7371.so:system/vendor/lib/libchromatix_imx318_primax_hfr_240_ak7371.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_hfr_60.so:system/vendor/lib/libchromatix_imx318_primax_hfr_60.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_hfr_60_ak7371.so:system/vendor/lib/libchromatix_imx318_primax_hfr_60_ak7371.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_postproc.so:system/vendor/lib/libchromatix_imx318_primax_postproc.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_preview.so:system/vendor/lib/libchromatix_imx318_primax_preview.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_snapshot.so:system/vendor/lib/libchromatix_imx318_primax_snapshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_primax_video_4k.so:system/vendor/lib/libchromatix_imx318_primax_video_4k.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_1080p_preview_lc898217.so:system/vendor/lib/libchromatix_imx318_semco_1080p_preview_lc898217.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_1080p_video_lc898217.so:system/vendor/lib/libchromatix_imx318_semco_1080p_video_lc898217.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_4k_preview_lc898217.so:system/vendor/lib/libchromatix_imx318_semco_4k_preview_lc898217.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_4k_video_lc898217.so:system/vendor/lib/libchromatix_imx318_semco_4k_video_lc898217.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_common.so:system/vendor/lib/libchromatix_imx318_semco_common.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_cpp_hfr_120.so:system/vendor/lib/libchromatix_imx318_semco_cpp_hfr_120.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_cpp_hfr_240.so:system/vendor/lib/libchromatix_imx318_semco_cpp_hfr_240.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_cpp_hfr_60.so:system/vendor/lib/libchromatix_imx318_semco_cpp_hfr_60.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_cpp_liveshot.so:system/vendor/lib/libchromatix_imx318_semco_cpp_liveshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_cpp_preview.so:system/vendor/lib/libchromatix_imx318_semco_cpp_preview.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_cpp_snapshot.so:system/vendor/lib/libchromatix_imx318_semco_cpp_snapshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_cpp_video.so:system/vendor/lib/libchromatix_imx318_semco_cpp_video.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_cpp_video_4k.so:system/vendor/lib/libchromatix_imx318_semco_cpp_video_4k.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_default_preview_lc898217.so:system/vendor/lib/libchromatix_imx318_semco_default_preview_lc898217.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_default_video_lc898217.so:system/vendor/lib/libchromatix_imx318_semco_default_video_lc898217.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_fullsize_preview_lc898217.so:system/vendor/lib/libchromatix_imx318_semco_fullsize_preview_lc898217.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_fullsize_video_lc898217.so:system/vendor/lib/libchromatix_imx318_semco_fullsize_video_lc898217.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_hfr_120.so:system/vendor/lib/libchromatix_imx318_semco_hfr_120.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_hfr_120_lc898217.so:system/vendor/lib/libchromatix_imx318_semco_hfr_120_lc898217.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_hfr_240.so:system/vendor/lib/libchromatix_imx318_semco_hfr_240.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_hfr_240_lc898217.so:system/vendor/lib/libchromatix_imx318_semco_hfr_240_lc898217.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_hfr_60.so:system/vendor/lib/libchromatix_imx318_semco_hfr_60.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_hfr_60_lc898217.so:system/vendor/lib/libchromatix_imx318_semco_hfr_60_lc898217.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_postproc.so:system/vendor/lib/libchromatix_imx318_semco_postproc.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_preview.so:system/vendor/lib/libchromatix_imx318_semco_preview.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_snapshot.so:system/vendor/lib/libchromatix_imx318_semco_snapshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_semco_video_4k.so:system/vendor/lib/libchromatix_imx318_semco_video_4k.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_snapshot.so:system/vendor/lib/libchromatix_imx318_snapshot.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libchromatix_imx318_video_4k.so:system/vendor/lib/libchromatix_imx318_video_4k.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libmmcamera_imx268.so:system/vendor/lib/libmmcamera_imx268.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libmmcamera_imx268_primax_eeprom.so:system/vendor/lib/libmmcamera_imx268_primax_eeprom.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libmmcamera_imx268_sunny.so:system/vendor/lib/libmmcamera_imx268_sunny.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libmmcamera_imx268_sunny_eeprom.so:system/vendor/lib/libmmcamera_imx268_sunny_eeprom.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libmmcamera_imx318.so:system/vendor/lib/libmmcamera_imx318.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libmmcamera_imx318_primax.so:system/vendor/lib/libmmcamera_imx318_primax.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libmmcamera_imx318_primax_eeprom.so:system/vendor/lib/libmmcamera_imx318_primax_eeprom.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libmmcamera_imx318_semco.so:system/vendor/lib/libmmcamera_imx318_semco.so \
    vendor/xiaomi/scorpio/proprietary/vendor/lib/libmmcamera_imx318_semco_eeprom.so:system/vendor/lib/libmmcamera_imx318_semco_eeprom.so

PRODUCT_PACKAGES += \
    qdcm_calib_data_lgd_sw43101_p2_video_fhd_oled_panel \
    qdcm_calib_data_lgd_sw43101_video_fhd_oled_panel
